package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	ctxApp "shoeshop-backend/src/interfaces/http/context"
	graph "shoeshop-backend/src/interfaces/http/graphql"
	"shoeshop-backend/src/interfaces/http/view/product"
)

// GetProducts is the resolver for the getProducts field.
func (r *queryResolver) GetProducts(ctx context.Context) ([]*product.Product, error) {
	appContext := ctxApp.GetAppCtxFromContext(ctx)

	return r.productView.GetAll(appContext)
}

// GetProduct is the resolver for the getProduct field.
func (r *queryResolver) GetProduct(ctx context.Context, id string) (*product.Product, error) {
	appContext := ctxApp.GetAppCtxFromContext(ctx)

	return r.productView.GetById(appContext, id)
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) GetList(ctx context.Context) ([]*product.Product, error) {
	appContext := ctxApp.GetAppCtxFromContext(ctx)

	return r.productView.GetAll(appContext)

}
